# Generated by Django 2.1.1 on 2018-10-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidora',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='app', verbose_name='imagen'),
        ),
    ]
